name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 启动 docker
        run: docker run --privileged=true -i -d --name=gcc --tmpfs /tmp -v 'work:/w' gcc:7.4.0 bash

      - name: 安装依赖
        run: |
          docker exec gcc bash -c 'apt update -qq'
          docker exec gcc bash -c 'apt-get install -qq git clang-tools-6.0 curl docutils-common gdb lcov libarchive-dev libtalloc-dev strace swig uthash-dev xsltproc'

      - name: 拉取存储库
        run: docker exec gcc bash -c "git clone https://gitlab.com/proot/proot.git /proot"

      - name: 构建
        run: |
          docker exec gcc bash -c 'LDFLAGS="${LDFLAGS} -static" make -C /proot/src proot'
          docker exec gcc bash -c "cp proot/src/proot /w/"
          sha256sum work/proot > work/proot.sha256sum
          md5sum work/proot > work/proot.md5sum

      - name: 下载产物
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: work/*
